name: Unpack stock-info repo (multi-part)
on:
  workflow_dispatch:
jobs:
  unpack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Reassemble
        run: |
          for i in {1..10}; do cat repo.part$(printf "%02d" $i) >> payload.b64; done
          base64 -d payload.b64 > payload.zip
          unzip -o payload.zip -d extracted
          cp -a extracted/. .
      - name: Commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add --all
          git commit -m "Unpacked multipart payload" || true
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          git push origin HEAD:main || true
